name: Playwright-Tests
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-and-run-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment: production
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3]
        shardTotal: [3]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run regression only
        if: github.event_name == 'push'
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: npx playwright test --project=tests --shard ${{ matrix.shardIndex }}/${{ matrix.shardTotal }} --workers 2

      - name: Upload blob report to GitHub Actions Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: merged-reports-as-blob
          path: blob-report
          retention-days: 90

      - name: Upload CTRF report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ctrf-report-${{ matrix.shardIndex }}
          path: ctrf
          retention-days: 90

  merge-reports-and-upload:
    if: always()
    needs: [setup-and-run-tests]
    runs-on: ubuntu-latest
    environment: production

    outputs:
      timestamp: ${{ steps.timestampid.outputs.timestamp }}

    steps:
      - name: Set a timestamp
        id: timestampid
        run: echo "timestamp=$(date --utc +%Y%m%d_%H%M%SZ)" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci

      - name: Install jq
        run: sudo apt-get install jq

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v3
        with:
          name: merged-reports-as-blob
          path: downloaded-merged-reports-as-blob

      - name: Download CTRF reports
        uses: actions/download-artifact@v4
        with:
          pattern: ctrf-report-*
          path: downloaded-ctrf-reports

      - name: Debug - List downloaded reports
        run: |
          echo "Contents of downloaded-ctrf-reports:"
          ls -R downloaded-ctrf-reports

      - name: Install CTRF CLI and merge reports
        run: |
          # Find all report files
          find downloaded-ctrf-reports -name "ctrf-report.json" -exec echo {} \; > report_paths.txt

          echo "Found report paths:"
          cat report_paths.txt

          # Create merge command with all reports
          merge_cmd="npx ctrf merge"
          while IFS= read -r report; do
            merge_cmd="$merge_cmd $report"
          done < report_paths.txt

          echo "Executing merge command: $merge_cmd --output-dir ./merged-reports"

          # Create output directory
          mkdir -p merged-reports

          # Execute merge
          $merge_cmd --output-dir ./merged-reports

          # Verify merge result
          echo "Merged report contents:"
          cat merged-reports/ctrf-report.json

      - name: List files in merged-reports
        run: |
          echo "Files in merged-reports directory:"
          ls -la merged-reports

      - name: Merge the blobs into one single HTML Report
        run: npx playwright merge-reports --reporter html ./downloaded-merged-reports-as-blob

      - name: Upload full html report to artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ steps.timestampid.outputs.timestamp }}
          path: playwright-report
          retention-days: 90

      - name: Push the new files to github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          destination_dir: ${{ steps.timestampid.outputs.timestamp }}

      - name: Write URL in summary
        id: report_url
        run: |
          reportUrl="https://${{ github.repository_owner }}.github.io/playwright_typescript/${{ steps.timestampid.outputs.timestamp }}/"
          echo "### Test results (link available after 20 secs) - $reportUrl" >> $GITHUB_STEP_SUMMARY
          echo "report_url=$reportUrl" >> $GITHUB_OUTPUT

      - name: Publish CTRF Test Summary Results
        run: npx github-actions-ctrf summary merged-reports/ctrf-report.json
        if: always()

      - name: Send Test Results to Slack
        if: always()
        run: |
          npx slack-ctrf results merged-reports/ctrf-report.json
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack channel of Playwright
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: playwright-project
          SLACK_COLOR: "#3278BD"
          SLACK_MESSAGE: "Playwright Test Report available: ${{ steps.report_url.outputs.report_url }}"
          SLACK_TITLE: Playwright Test Report
          SLACK_USERNAME: Github Action Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
